-- AarogyaMitra Supabase hardening / RLS / Realtime setup.
-- Run AFTER the FastAPI app has created the tables, or create the tables first from the ORM.

alter table public.users enable row level security;
alter table public.revoked_tokens enable row level security;
alter table public.conversations enable row level security;
alter table public.health_states enable row level security;
alter table public.reports enable row level security;
alter table public.health_timeline enable row level security;
alter table public.followups enable row level security;
alter table public.handoffs enable row level security;
alter table public.emergency_events enable row level security;
alter table public.ai_events enable row level security;
alter table public.dashboard_signals enable row level security;
alter table public.audit_logs enable row level security;

alter table public.users add column if not exists memory_enabled boolean default true;

grant select on public.dashboard_signals to anon, authenticated;
drop policy if exists "dashboard signals are readable" on public.dashboard_signals;
create policy "dashboard signals are readable" on public.dashboard_signals for select using (true);

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='dashboard_signals') then
    alter publication supabase_realtime add table public.dashboard_signals;
  end if;
end $$;

-- Sensitive patient/application tables intentionally have no anon/authenticated policies here.
-- The FastAPI backend connects with the database connection string and enforces application authorization.
-- Create a PRIVATE Storage bucket named aarogyamitra-reports for generated documents.

-- v11 AI quality + consent tables
create table if not exists public.consents (
  id bigint generated by default as identity primary key,
  user_id varchar(80) not null references public.users(user_id) on delete cascade,
  consent_type varchar(50) not null,
  granted boolean not null default false,
  version varchar(20) not null default '1.0',
  updated_at timestamp not null default now()
);
create index if not exists idx_consents_user on public.consents(user_id);
create unique index if not exists uq_consent_user_type on public.consents(user_id, consent_type);
alter table public.consents enable row level security;

create table if not exists public.ai_evaluations (
  id varchar(80) primary key,
  scenario_id varchar(80) not null,
  prompt text not null,
  response text not null,
  passed boolean not null default false,
  issues jsonb not null default '[]'::jsonb,
  expected jsonb not null default '[]'::jsonb,
  created_at timestamp not null default now()
);
create index if not exists idx_ai_evaluations_created on public.ai_evaluations(created_at desc);
alter table public.ai_evaluations enable row level security;
