create table if not exists public.consents (
  id bigint generated by default as identity primary key,
  user_id varchar(80) not null references public.users(user_id) on delete cascade,
  consent_type varchar(50) not null,
  granted boolean not null default false,
  version varchar(20) not null default '1.0',
  updated_at timestamp not null default now()
);
create index if not exists idx_consents_user on public.consents(user_id);

create table if not exists public.ai_evaluations (
  id varchar(80) primary key,
  scenario_id varchar(80) not null,
  prompt text not null,
  response text not null,
  passed boolean not null default false,
  issues jsonb not null default '[]'::jsonb,
  expected jsonb not null default '[]'::jsonb,
  created_at timestamp not null default now()
);
create index if not exists idx_ai_evaluations_created on public.ai_evaluations(created_at desc);

alter table public.consents enable row level security;
alter table public.ai_evaluations enable row level security;
